### PR TITLE
Issue#9

### LINKED ISSUE #9: Rewrite internal coordinate system?
Currently the coordinates are represented in the format `x = 124, y = 121` instead of `x = 31744, y = 30976`, meaning we have to convert them to the latter format every time we want to display them. Switching to the latter format internally might simplify things and make it easier to add a “markers” layer later on.

Resources that might be useful:
- http://leafletjs.com/examples/crs-simple/crs-simple.html

### PR DESCRIPTION
**Pull request by Bernardoow**
I don't rewrite the internal cordinates system. I Just used internal function of _Leftletjs_  projection, that use the zoom level (always 0 -> 256) to calculate the  tibia cordinates.

Fixes #9

### CODE REVIEW

**Comment by Bernardoow** [comment]
I used JS function objects.keys  [doc](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Object/keys). Browser compatibility for IE is =>9 .

**Comment by mathiasbynens** [comment]
When dragging the map around, then moving the mouse, this happens:



Can we do something about that?

**Comment by Bernardoow** [comment]
@mathiasbynens 

Uhm.. When you drag and happned for few secons after? It its?

**Comment by mathiasbynens** [comment]
Yeah. I worked around it by doing this: https://github.com/tibiamaps/tibia-map/commit/96cd633ba7db3c21d14f0766b94ebc1e45c49984#diff-2b6714cd55551e97361a5646888078ffR261

**Comment by Bernardoow** [comment]
Ok. Sorry for that.

When I tested I din't saw it. 

Yesterday I tested this problem, that happen for fews seconds.
If move mouse to another place and go back to same title with error, in second moment the coordenates is displayed with correct informations .

Your solution was good, uses the same code that is used in previous version.
In next weekend I will study leftjs about this situation.

**Pull request closed without merging**
