### PR TITLE
Added a small logic to enable the fullscreen btn using data-attribute.

### PR DESCRIPTION
**Pull request by Bernardoow**
#33

### CODE REVIEW

**Comment by mathiasbynens** [comment]
Bernardo, this is unrelated to this patch, but I remember you helped out a lot with the TibiaMaps.io map viewer in the past. What is your Tibia character?

**Comment by Bernardoow** [comment]
Hi @mathiasbynens, morning !!

I tried to help the fansite hehe but.. nearly always .. my ideas wasn't good enough to be a feature kkk

I'm Angel Shanar .

**Comment by mathiasbynens** [comment]
> Hi @mathiasbynens, morning !!
> 
> I tried to help the fansite hehe but.. nearly always .. my ideas wasn't good enough to be a feature kkk
> 
> I'm Angel Shanar .

Hi Bernardo, please log in to the game and check your inbox :)

**Comment by Bernardoow** [comment]
Hi @mathiasbynens !!

I'm so happy !! Thanks very much !!

Its amazing !! You are so cool !!

If you need help with something, let me know and I'll be here to help you!!

**Comment by mathiasbynens** [comment]
Glad to hear it :) Thank you for all your contributions to the TibiaMaps.io map viewer over the years!

**Pull request closed without merging**
